### ISSUE TITLE
Go to Definition (routes) not working in Windows

### ISSUE THREAD

**Issue by FreezinG117** [tiansin/vscode-laravel-assist#1]
Hi!

When I try "Go to Definition" it returns the following error:
![error image](https://user-images.githubusercontent.com/8019593/56804758-b5357d80-681e-11e9-9062-ecdcc7175177.png)

The Controller exists and it is in following path:
> C:\\_dev\LookAfterRisk\LookAfterRiskWebsite\app\Http\Controllers

Notice that in the error message there's no drive (C:)

[Video Demonstrating problem](https://transfer.sh/14DpLr/laravel.mp4)

---

VS Code 1.33.1
Windows 10 Pro 1809

**Comment by tiansin** [comment]
🎉 This issue has been resolved in version [0.1.5](https://marketplace.visualstudio.com/items?itemName=tiansin.vscode-laravel-assist) 🎉
